export const actionCatalog = [
  ["terminal.new", "Nueva terminal", "Terminal", ["Ctrl+Shift+T"]],
  ["terminal.close", "Cerrar terminal", "Terminal", ["Ctrl+Shift+W"]],
  ["terminal.split", "Dividir en columnas", "Terminal", ["Ctrl+Shift+D"]],
  ["terminal.splitRows", "Dividir en filas", "Terminal", ["Ctrl+Shift+E"]],
  ["terminal.clear", "Limpiar pantalla local", "Terminal", []],
  [
    "terminal.search",
    "Buscar en terminal",
    "Terminal",
    ["Ctrl+F", "Ctrl+Shift+G"],
  ],
  ["terminal.copy", "Copiar selección", "Terminal", ["Ctrl+Shift+C"]],
  ["terminal.paste", "Pegar en terminal", "Terminal", ["Ctrl+Shift+V"]],
  ["terminal.export", "Exportar salida de terminal", "Terminal", []],
  ["terminal.focus", "Modo enfoque", "Terminal", ["Ctrl+Shift+F"]],
  ["command.focus", "Enfocar barra de comandos", "Terminal", ["Ctrl+Space"]],
  [
    "commandPalette.open",
    "Paleta de comandos",
    "Navegación",
    ["Ctrl+Shift+P", "Ctrl+K"],
    "global",
  ],
  ["settings.open", "Preferencias", "Navegación", []],
  ["shortcuts.open", "Atajos de teclado", "Navegación", [], "global"],
  ["toolbox.open", "Herramientas", "Navegación", ["Ctrl+Alt+T"]],
  ["apiTester.open", "Abrir API Tester", "API", ["Ctrl+Alt+C"]],
  ["dataTools.open", "JSON / YAML / XML", "Datos", ["Ctrl+Alt+J"]],
  ["portInspector.open", "Puertos y procesos", "Sistema", ["Ctrl+Alt+P"]],
  ["apiTester.repeat", "Repetir última petición", "API", []],
  ["snippets.open", "Snippets parametrizados", "Snippets", ["Ctrl+Alt+S"]],
  ["snippets.new", "Nuevo snippet", "Snippets", []],
  ["workspace.new", "Nuevo espacio de trabajo", "Espacios", []],
  ["workspace.save", "Guardar espacio", "Espacios", ["Ctrl+Shift+S"]],
  ["workspace.rename", "Renombrar espacio", "Espacios", []],
  ["explorer.toggle", "Mostrar u ocultar explorador", "Navegación", []],
  ["context.toggle", "Mostrar u ocultar contexto", "Navegación", []],
  ["git.open", "Abrir cambios y ramas Git", "Git", []],
  ["editor.open", "Abrir archivo en editor", "Archivos", []],
  ["editor.fileOpen", "Abrir archivo", "Editor", ["Ctrl+O"], "editor"],
  ["editor.new", "Nuevo archivo", "Editor", ["Ctrl+N"], "editor"],
  ["editor.save", "Guardar archivo", "Editor", ["Ctrl+S"], "editor"],
  [
    "editor.saveAs",
    "Guardar archivo como",
    "Editor",
    ["Ctrl+Shift+S"],
    "editor",
  ],
  ["editor.close", "Cerrar editor", "Editor", ["Ctrl+W"], "editor"],
  ["editor.search", "Buscar en archivo", "Editor", ["Ctrl+F"], "editor"],
  ...Array.from({ length: 8 }, (_, i) => [
    `terminal.tab${i + 1}`,
    `Abrir pestaña ${i + 1}`,
    "Terminal",
    [`Alt+${i + 1}`],
  ]),
].map(([id, label, category, shortcuts, context = "terminal"]) => ({
  id,
  label,
  category,
  shortcuts,
  context,
}));
export function registerCatalog(r, handlers, enabled = {}) {
  for (const a of actionCatalog)
    r.register({ ...a, run: handlers[a.id], enabled: enabled[a.id] });
}
